//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace L2_podejscie_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "this field is required.")]
        public string Login { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "this field is required.")]
        public string Password { get; set; }
        [Required(ErrorMessage = "this field is required.")]
        public string Name { get; set; }
        [Required(ErrorMessage = "this field is required.")]
        public string Surname { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }

        public string ErrorMessage { get; set; }
    }
}
